### ISSUE TITLE
Restore previous winbar instead of `= nil` if filetype is excluded

### ISSUE THREAD

**Issue by fnune** [Ramilito/winbar.nvim#6]
https://github.com/Ramilito/winbar.nvim/blob/main/lua/winbar/init.lua#L96

In here, the previous winbar is set to `nil`. This breaks things like e.g. dap-ui:

![image](https://github.com/Ramilito/winbar.nvim/assets/16181067/239638ea-a730-4d98-a5e6-85c2ad96712c)
_Before hovering the `dap-repl` window at the bottom_

![image](https://github.com/Ramilito/winbar.nvim/assets/16181067/8fb8fd31-e102-4a57-afa5-67ff6711cbe3)
_After hovering it_

I'd expect the winbar not to change its contents if `winbar.nvim` has the filetype in `filetype_exclude`.

**Comment by Ramilito** [comment]
Yeah that feels wrong, it should leave the winbar alone if excluded, I'll remove it!

**Comment by Ramilito** [comment]
Fixed in commit 6379501
