### ISSUE TITLE
Filetype exclude broken

### ISSUE THREAD

**Issue by Saghen** [Ramilito/winbar.nvim#7]
The most recent commit seems to have broken filetype exclusion on my system (test with `nvimdev/dashboard-nvim`): https://github.com/Ramilito/winbar.nvim/commit/637950156d12a7cb90606cd27b4269c7a91c65c1

**Comment by Ramilito** [comment]
Thank you for reporting it!
There seem to have been race conditions when another plugin sets filetype on VimEnter event so when we check for filetype the first time (same time as dashboard) the filetype would not be dashboard, this was previously solved by unsetting it on BufEnter later on.
I added a vim.defer_fn and a mark to decide whether to unset the winbar or not.
